development:
  oauth:
    github:
      _secure_id: b567639aef9988970767
      _secure_secret: f7f6f58552328bec0b0d035adb811beda8fbc296

test:
  oauth:
    github:
      id: TEST
      secret: TEST

production:
  oauth:
    github:
      id: TODO
      secret: TODO
