development:
  oauth:
    github:
      _secure_id: wCU7ojf9VjJsqOotCS7pis2IueCZrML67QeFukndBaxDYS8JnpXBIJKt8I+mIIMJ5gpPjvBTNg9Y6t1Ji4JPyxcaiaXuWwOpQ4G76GW5HsSkowOhOf9RO0DQtPLFaFZI6sYo3tVZNkw8zrCmcAXL9XnF7hrjlLhX9FyUU7i8oTMq70UurpDWIXT59VtvNG8R3tOTrSwnAOms0i/GsI3Ajy53xK9zTql1ZqKVUFlRWmvWbRtlrQ6KXxXLY5p2XcdyMJzZnAANojBReO63PW0AUeZEUYdrjHEPTPv+M/upNmPzmc0cEBuGLROK/2n9s/AD63C8ktb2c2QHxZQT1tOVWA==
      _secure_secret: yDXorTh577+7mhGS+j/f7wZr30zqr1L5TQ8UHxQwSx89BKleydub5qz5JFGI4IsecW7GRSBZ84ADv2MtlACnhBr8fi7nrqYRwhSfhcF/gO2wIEZKas442i9UG3SkESOs7XYozftnzeDWqsGYaKZ3HSXD8sdCl79xMVKoCXdgpi1KeKcpe8L1bJD88A5Ii1gMLEEYBFiE9H9mTyemhB7HuTKhCG05+X+BCwfqNi5NCH94N1XElBlO3+nrQxW+nw57duV+JQRbx1WEPzIjUoAOOZCIj2UddASzmvNcSJmf5rYOJ8FeZXDEda5Qm/v31FTfehpmUwdpgW4LeT5ITbYeqA==

test:
  oauth:
    github:
      id: TEST
      secret: TEST

production:
  oauth:
    github:
      id: TODO
      secret: TODO
